# API Configuration
companies_house:
  api_key: "YOUR_COMPANIES_HOUSE_API_KEY"
  base_url: "https://api.company-information.service.gov.uk"
  rate_limit: 600  # requests per 5 minutes

openai:
  api_key: "YOUR_OPENAI_API_KEY"
  model: "gpt-4"
  max_tokens: 1000

databricks:
  host: "YOUR_DATABRICKS_HOST"
  token: "YOUR_DATABRICKS_TOKEN"
  cluster_id: "YOUR_CLUSTER_ID"

# Data Sources
external_apis:
  duedil:
    api_key: "YOUR_DUEDIL_API_KEY"
    base_url: "https://duedil.io/v4"
  
  creditsafe:
    username: "YOUR_CREDITSAFE_USERNAME"
    password: "YOUR_CREDITSAFE_PASSWORD"
    base_url: "https://connect.creditsafe.com/v1"

# ML Model Configuration
models:
  sector_classification:
    model_name: "sector_classifier_v1"
    confidence_threshold: 0.7
  
  turnover_estimation:
    model_name: "turnover_estimator_v1"
    confidence_threshold: 0.6

# Processing Configuration
processing:
  batch_size: 1000
  max_workers: 4
  timeout: 30
